
addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - CHEF_VERSION=13 INSTANCE=default-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=default-ubuntu-1804
  - CHEF_VERSION=13 INSTANCE=default-debian-8
  - CHEF_VERSION=13 INSTANCE=default-debian-9
  - CHEF_VERSION=13 INSTANCE=default-centos-6
  - CHEF_VERSION=13 INSTANCE=default-centos-7
  - CHEF_VERSION=13 INSTANCE=default-fedora-latest
  - CHEF_VERSION=13 INSTANCE=source-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=source-ubuntu-1804
  - CHEF_VERSION=13 INSTANCE=source-debian-8
  - CHEF_VERSION=13 INSTANCE=source-debian-9
  - CHEF_VERSION=13 INSTANCE=source-fedora-latest
  - CHEF_VERSION=13 INSTANCE=source-centos-7
  - CHEF_VERSION=14 INSTANCE=default-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=default-ubuntu-1804
  - CHEF_VERSION=14 INSTANCE=default-debian-8
  - CHEF_VERSION=14 INSTANCE=default-debian-9
  - CHEF_VERSION=14 INSTANCE=default-centos-6
  - CHEF_VERSION=14 INSTANCE=default-centos-7
  - CHEF_VERSION=14 INSTANCE=default-fedora-latest
  - CHEF_VERSION=14 INSTANCE=source-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=source-ubuntu-1804
  - CHEF_VERSION=14 INSTANCE=source-debian-8
  - CHEF_VERSION=14 INSTANCE=source-debian-9
  - CHEF_VERSION=14 INSTANCE=source-fedora-latest
  - CHEF_VERSION=14 INSTANCE=source-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
